# Introduction {#intro}

## Curriculum and grading

This course is part of either *Fachinhaltliche Vertiefung I* or *Fachinhaltliche Vertiefung II*. Its main rational is to give you the opportunity to delve into an exciting topic of your choice. You will

-   write a systematic literature review on it (70% of your mark)
-   defend your paper (30% of your mark)

To receive credit for this seminar, you are required to:

- **Attend regularly** (at least 80%)  
- **Participate actively**, including:  
  - Reading the material in advance (no reading time during sessions)  
  - Completing in-class assignments (e.g. team discussions, feedback, reviews, etc.)


## Intended learning outcomes

- Write a systematic literature review on a topic within the scope of the seminar.  
- Use AI ethically and transparently to assist your work.  
- Apply structural reading to scientific literature.  
- Apply methods of scientific writing to your seminar paper, including:  
  - Systematic literature search using databases  
  - Selection of relevant literature  
  - Summary of research results while avoiding plagiarism  
  - Critical evaluation  
- Provide professional, written peer feedback on your peers’ work.  
- Defend and discuss your paper professionally.



## Classroom values

-   Be on time for live meetings and for submitting assignments.
-   Be prepared for an active participation (do the assignments!)
-   Respect others' opinion.
-   Be open to changing your perspective.
-   Be open to topics and methods that might be unfamiliar to you.


<br> Be patient with the new digital format of the course and your lecturer! <i class="fa-solid fa-face-smile" style="color:#f5b700; text-shadow: 0 0 2px #000;"></i>







