# Systematic literature review


## PRISMA appraoch

In this seminar, we will follow the PRISMA approach to write the systematic literature review.


## Literature search
We will use the following literature databases mandatorily:

1. [Web of Science](https://apps.webofknowledge.com/) 
2. [Scopus](https://www.scopus.com)

You can complement your literature search by:

- [Google Scholar](https://scholar.google.com/) 
- [Research Rabit](https://www.researchrabbit.ai/)
- [Eilicit](https://elicit.com/)
- [Incietful](https://inciteful.xyz/)
- ...


For [Web of Science](https://apps.webofknowledge.com/), either [create an account](https://webofscience.zendesk.com/hc/en-us/articles/20011617329425-Registering-and-Signing-in-to-the-Web-of-Science#h_01K209WP4SJAK2A3XA0WC1SZNZ) and link it to UoC or activate your [VPN client](https://rrzk.uni-koeln.de/internetzugang-web/netzzugang/vpn) when accessing from outside the university.

Similarly, to access [Scopus](https://www.scopus.com), you will need your VPN client.

## General structure and length of your review

Your review **must** be structured as follows:

- Title page contains: your name, your matriculation number, the title of the seminar, the name of your lecturer and the submission date
- Abstract: write a structured abstract. It consists of background information, knowledge gap, methods used, results, conclusions. Every point is 2--3 sentences long. In other words, you rewrite your paper in miniature format.
- Keywords: 4--6
- Table of content
- Introduction: provide the background for your topic. Why is it relevant? Why is a review necessary? What is the research question or the goal of your review?
- Method: summarize your literature search here. When did you the search? In which databases? Which keywords did you use? How did you exclude irrelevant papers?
- Main part: you can name it differently, depending on your topic. In this part, you present your results. In most cases, you will subdivide this section in several subsections
- Discussion: Discuss critically your topic and the results you have summarized in the Main part. The focus is not on rating the papers, but on critical assessment of their content. Answer your research questions!
- Conclusions: Summary and take-home messages.
- References

If you use many abbreviations, put a list of abbreviations after the keywords.

Your review should be between 4000 and 6000 words (excluding abstract, keywords, table of contents, list of abbreviations and references). 

## Software {#software}
You can select any free or commercial word-processing software, e.g. [LibreOffice](https://www.libreoffice.org/), [Open Office](http://www.openoffice.org/de/), [LaTeX](https://www.latex-project.org/) or MS Word. However, be sure to correctly **connect your word processor to your bibliography manager**. Do not copy and paste references manually because this is very error-prone, and you risk forgetting citations.

You are also free to select any reference management software. The free [Zotero](https://www.zotero.org/) is recommended, but the UoC also provides licences for [Citavi](https://itcc.uni-koeln.de/en/services/software/rahmenvertraege-und-campuslizenzen/wissenschaftliche-anwendungen/citavi) and [Endnote](https://itcc.uni-koeln.de/en/services/software/rahmenvertraege-und-campuslizenzen/wissenschaftliche-anwendungen/endnote) to manage your bibliography.

In case you decide to use Zotero, there is a helpful [video tutorial](https://www.youtube.com/watch?v=Hm0TboOcAuM&list=PLScSkCQ_d7EOSU6n682bwjTC6GjY_ihmM) explaining how to use it and how to connect it to your word-processing software.

We will use the citation style Elsevier - Vancouver (author-date; sorted alphabetical) In Zotero and Geomorphology in Endnote. You can download the style for Zotero [here](https://www.zotero.org/styles?q=elsevier&dependent=0) and for Endnote [here](https://endnote.com/style_download/geomorphology/). If you want to use Citavi, you have to [find](https://www1.citavi.com/sub/manual5/en/cse_finding_citation_styles.html) an appropriate style yourself.

## Plagiarism
You will have a blended learning unit on plagiarism and how to avoid it. We will exercise paraphrasing during the seminar.


