# Scientific English {#scientific-english}

## How to write clear scientific English?

The material in this section is based on @Skern2019. He suggests 8 guidelines that will help you to write in a clear and concise way:

1. Plan your writing
2. Use a clean and legible layout
3. Structure your text in paragraphs
4. Write simple sentences
5. Write positive statements
6. Write active statements
7. Omit unnecessary words
8. Read, think, write, read again and think again

## Paraphrasing of longer texts
Every sentence you paraphrase or idea you take from others' work must be references. The reader should be able to distinguish between your ideas and thoughts and others' contributions. To avoid placing references after every sentence, you might use the following style:

```{block, type = 'rmdexample'}
X and Y explain in *their paper* that agricultural fields were contaminated by microplastics (**reference**). This is a global rather than local issue so *the authors*. Therefore, *they* suggest to implement a global monitoring programm to tackle micropalstics contamination. In *the same paper*, X and Y mention that to reduce littering of microplastics the production of one-way plastics must be reduced.
```

It is clear that all the content comes from X and Y although the reference itself appears only once in the text.

Other helpful expressions for paraphrasing:

- according to the work of $\dots$
- our results accord well with $\dots$
- X and Y suggest $\dots$
- this result is also supported by X and Y (reference)


## Further reading and excercises
Read chapter 2 in @Skern2019 and do the exercises. Compare your solutions to his suggestions.



