# Blended learning units

## Unit 1: Effective reading

### SQ4R method
Introducing the SQ4R method for effective reading.

<iframe width="641" height="360" src="https://www.youtube.com/embed/ziofH7N8ZOE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Assignments
1. Answer the Quiz on ILIAS.

1. Read [Part III: Writing a Literature Review](JYI_Guide_to_Scientific_Writing.pdf) from the Journal of Young Investigators [@JournalofYoungInvestigators2005] using the SQ4R method. Then, upload your SQ4R notes on ILIAS.


<br>
<br>

## Unit 2: Literature search {#lit-search}

### Install a reference management software
Refer to chapter [Software](#software) and install the reference management software. I recommend Zotero and can provide some support in case of major issues.

### Data base Web of Science
Start by an overview of Web of Science (WoS): http://clarivate.libguides.com/webofscienceplatform. Then, create a profile. This allows you to save your searches and access from outside the UoC for 6 months. Watch the video below on how to create a profile.

<iframe width="641" height="360" src="https://www.youtube.com/embed/H5Rw7iHEYOw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Once you have registered and created a profile, start to search for literature. The two videos below show how to do this and provide tips on how to combine different keywords for an effective search.

<iframe width="641" height="360" src="https://www.youtube.com/embed/U6IZ8_OQeu8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="641" height="360" src="https://www.youtube.com/embed/xwhy0JBHlMw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Assignments
1. Create a new library (or collection in case you use Zotero) in your reference management software.

1. Search WoS for at least 3 relevant publications on your seminar topic.

1. Upload a screenshot of your bibliography in ILIAS.

<br>
<br>

## Unit 3: Your role as a peer reviewer
Do the module [Your role as a peer reviewer](https://masterclasses.nature.com/focus-on-peer-review-online-course/16605550) of the free Nature master class "Focus on peer review". You will need to register first.

<br>
<br>


## Unit 4: Plagiarism
### What is plagiarism and how to avoid it
There are many ways to define plagiarism. However, they all include basically the same aspects. Read the definition of plagiarism from the Appendix H in @Darr2019: "Combating Plagiarism: a Hands-On Guide for Librarians, Teachers, and Students". You can access the whole book [here](https://ebookcentral.proquest.com/lib/ubkoeln/detail.action?docID=5896173). Don't forget to activate your VPN client when accessing from outside the UoC.

### Paraphrasing
A crucial step in avoiding plagiarism is to learn to paraphrase the original source correctly and give a correct citation. While citing correctly is largely facilitated by the reference management software, paraphrasing has to be practised.

### Common knowledge
Not every idea you use in your paper needs to be cited. Common knowledge does not need any reference. However,  you cannot copy it verbatim. Thus, it is important to learn to distinguish between citable information (that will be either paraphrased or quoted) and common knowledge. What constitutes common knowledge, can depend on the context and the audience you address. In our case, you can consider your audience to be (reasonably well) educated science graduates.

### Assigments
1. Read pp. 17--22 in Chapter 2 "Paraphrasing and Micro-Paraphrasing" by @Darr2019 using the SQ4R method and take notes. Bring your notes to the next class.

1. Look at the following examples and decide whether the information (i) constitutes common knowledge and only needs to be paraphrased, (ii) should be paraphrased and cited or (iii) quoted directly and cited. For every example, write a justification and submit it to ILIAS.

- Bogner (2014): Landslides are a ubiquitous phenomenon in mountainous regions.

- Bogner (2014): Image indices are real-valued functions in the range [0, 1] that calculate certain properties of binary images and thus provide quantitative information about the morphology of flow patterns.

- Nülle (2014): Following the invention of the first modern plastic “Bakelit” in 1907, inexpensive high-volume manufacturing techniques were developed.

- https://sustainabledevelopment.un.org/: The 17 Sustainable Development Goals (SDGs) were adopted by all United Nations Member States in 2015 and aim at improving living condition by 2030 while protecting the environment.

- https://sustainabledevelopment.un.org/sdg5: Sustainable Development Goal 5: Achieve gender equality and empower all women and girl.

<br>
<br>

## Unit 5: The peer review report
Do the module [The peer review report](https://masterclasses.nature.com/focus-on-peer-review-online-course/16605550) of the free Nature master class "Focus on peer review". You will need to register first.