--- 
title: "Current Topics in Ecosystem Research"
subtitle: "Seminar spring term 2020"
author: "Christina Bogner"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "This is companion book for the seminars of the working group Ecosystem Research"
---

# Prerequisites

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
The corona virus pandemic impacts our lives and changes the way we teach and learn. This course will start as an online course and depending on the situation will or will not turn into a traditional seminar. Please be patient if not all activities turn out to be successful and not all technical tools function as desired. We all will do our best to support you in your curriculum.
</div>

<br>

In this seminar we will use different tools for communication:

1. **ILIAS**: the e-learning platform of the university. You should have been registered automatically for the course.
2. **Campuswire**: the online chat and communication platform. You should have received an invitation to join.
3. **Zoom**: the video conference tool for live sessions. The link to the zoom meeting room and detailed instructions can be found on the ILIAS website.
