--- 
knit: "bookdown::render_book"
title: "Current Topics in Ecosystem Research"
subtitle: "Seminar summer term 2021"
author: "Christina Bogner"
date: "Last updated: `r format(Sys.time(), '%Y-%m-%d')`"
site: bookdown::bookdown_site
#output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: true
github-repo: https://github.com/ChrisBogner/seminar_companion.git
description: "This is companion book for the seminars of the working group Ecosystem Research"
---

# Prerequisites {.unnumbered}

```{block, type='rmdinfo'}
The corona virus pandemic impacts our lives and changes the way we teach and learn. This course will be held online. Please be patient if not all activities turn out to be successful and not all technical tools function as desired. We all will do our best to support you in your curriculum.
```

In this seminar we will use different tools for communication:

1. **ILIAS**: the e-learning platform of the university. You should have been registered automatically for the course.
2. **Campuswire**: the online chat and communication platform. You should have received an invitation to join.
3. **Zoom**: the video conference tool for live sessions. The link to the zoom meeting room and detailed instructions can be found on the ILIAS website.

In this companion, we will use blocks to highlight particular content

```{block, type='rmdinfo'}
This is an info block.
```

<br>

```{block, type='rmdalert'}
This is an alert block.
```

<br>

```{block, type='rmdexample'}
This is an example block.
```

## Where has this course been taught? {.unnumbered}

- University of Cologne, summer term 2020 for MSc Geography


<!--chapter:end:index.Rmd-->

# Introduction {#intro}
## Curriculum and grading

This course is part of either *Fachinhaltliche Vertiefung I* or *Fachinhaltliche Vertiefung II*. Its main rational is to give you the opportunity to delve into a exciting topic of your choice. You will 

- present this topic to your peers (30% of your mark)
- write a critical literature review on it (70% of your mark)


## Intended learning outcomes

- Apply structural reading (SQ4R) to scientific literature.
- Present professionally and discuss a topic in the scope of the seminar.
- Write a critical literature review on a topic in the scope of the seminar.
- Apply methods of scientific writing to your seminar paper
	- systematic literature search using data bases
	- selection of relevant literature
	- summary of research results avoiding plagiarism
	- critical evaluation
- Give peer feedback to your peers' work professionally in written form.

## Class room values

- Be on time for live meetings and for submitting assignments.
- Be prepared for an active participation (do the assignments!)
- Respect others' opinion.
- Be open to changing your perspective.
- Be open to topics and methods that might be unfamiliar to you.

<br>
Be patient with the new digital format of the course and your lecturer! `r emo::ji('smile')`

<!--chapter:end:01-intro.Rmd-->

# Presentation {#presentation}

## Presenting student


We will establish more detailed criteria of a good scientific presentation during the seminar. Thus, the following requirements are general and a strict minimum:


**Content**

- Title slide (title, your name, title of the seminar)
- Motivation slide: Why is this topic relevant and why does it need a critical review
- Body of your presentation: Here, you give information on your topic
- Critical evaluation or discussion
- Take-home messages: Summarize the most important aspects
- References: you prepare, but do not show this slide

```{block, type = 'rmdalert'}
Cite the literature and all figures/tables/data you use correctly!
```


**Time**

You have **15 minutes** to present your topic. Afterwords, we will have a group discussion.

**Feedback**

You will receive feedback from your peers in form of one-minute papers through campuswire. Therefore, in `class feed`, post the title of your presentation. Your peers will respond to this post with their feedback.


## Peers
Listen carefully and critically to the presenter and provide *anonymous* feedback through campuswire. Structure your feedback as follows:

1. The main points of the presentation: Summarize what you understood in 2--3 sentences. The presenter should see whether his/her take-home messages were received.
2. State which concrete issues you observed (see feedback rules below)
3. Suggest concrete ways to improve and further aspects to include in the review paper.


## Feedback rules
### How to give feedback
A peer feedback should always be provided as a *personal opinion* and communicated accordingly. A peer feedback, both written and oral is

- respectful
- me-centered
- addresses a concrete observation
- tells what it did to the feedback provider
- provides a doable suggestion

```{block, type = 'rmdexample'}
On slide 4, you explained that carbon sequestration in the soil depended on temperature. I am not familiar with this and did not understand the relationship to climate change. Could you please explain this in your paper in more detail. For your paper, you could also include the aspect of increasing CO~2~ in the atmosphere and ocean acidification.
```

### How to receive feedback
Remember that the feedback is a *personal opinion*. Therefore,

- don't take it personally
- don't apologize
- take it and say thank you
- you decide whether you want to implement this feedback


<!--chapter:end:02-presentation.Rmd-->

# Literature review

## Literature search
Use the literature data base [Web of Science](https://apps.webofknowledge.com/) or [Google Scholar](https://scholar.google.com/) to find your literature. You will have a blended learning unit on how to use the data bases. For [Web of Science](https://apps.webofknowledge.com/), either create an account and link it to UoC or activate your [VPN client](https://rrzk.uni-koeln.de/internetzugang-web/netzzugang/vpn) when accessing from outside the university.

## General structure and length of your review

Your review must be structured as follows:

- Title page: contains your name, the title of the seminar, the name of your lecturer and the submission date
- Abstract
- Key words
- Table of content
- Introduction
- Method
- Main part
- Discussion
- Conclusions
- References

Your review should be between 3000 and 6000 words in the main part (i.e. without abstract, table of contents, references etc.). 

## Software
You can select any free or commercial word processing software, e.g. [Libre Office](https://www.libreoffice.org/), [Open Office](http://www.openoffice.org/de/), [LaTeX](https://www.latex-project.org/) or [Word](https://rrzk.uni-koeln.de/software-multimedia/software/rahmenvertraege-und-campuslizenzen/microsoft/office-fuer-studierende). However, be sure to correctly **connect your word processor to your bibliography manager**. Do not copy and paste references manually because this is very error prone and you risk to forget citations.

You are also free to select any reference management software. The free [Zotero](https://www.zotero.org/) is recommended, but the UoC also provides licences for [Citavi](https://rrzk.uni-koeln.de/software-multimedia/software/rahmenvertraege-und-campuslizenzen/citavi) and [Endnote](https://rrzk.uni-koeln.de/software-multimedia/software/rahmenvertraege-und-campuslizenzen/endnote) to manage your bibliography.

In case you decide to use Zotero, there is a helpful [video tutorial](https://www.youtube.com/watch?v=Hm0TboOcAuM&list=PLScSkCQ_d7EOSU6n682bwjTC6GjY_ihmM) explaining how to use it and how to connect it to your word processing software.

We will use a citation style close to the one used by the journal Geomorphology. You can download the style for Zotero [here](https://www.zotero.org/styles?q=elsevier&dependent=0) and for Endnote [here](https://endnote.com/style_download/geomorphology/). If you want to use Citavi, you have to [find](https://www1.citavi.com/sub/manual5/en/cse_finding_citation_styles.html) an appropriate style yourself.

## Plagiarism
You will have a blended learning unit on plagiarism and how to avoid it. We will exercise paraphrasing during the seminar.

I will check your paper draft for plagiarism with [turnitin](https://www.turnitin.com/) and give you detailed feedback. The final paper will also be checked for plagiarism. Plagiarism will result in a worse grade and substantial plagiarism in failing the seminar.


<!--chapter:end:03-lit_review.Rmd-->

# Helpful literature

To help you writing your literature review, you should consult the suggested reading material. It will cover different aspects of writing. @Beinke2016 provides a very general guide to writing a seminar paper.

## How to write a literature review
- @Pautasso2013: Ten Simple Rules for Writing a Literature Review

## How to improve your scientific English
- @Skern2011: Writing Scientific English. You can access this book via the UoC library. Be sure to activate your [VPN client](https://rrzk.uni-koeln.de/internetzugang-web/netzzugang/vpn) when accessing from outside the university.

## How to prepare and give a good scientific presentation
The general structure of your presentation is given and fixed (see chapter \@ref(presentation)). For more detailed information, you can find helpful web resources by Nature, for example

- Scientific presentations: A cheat sheet: http://blogs.nature.com/naturejobs/2017/01/11/scientific-presentations-a-cheat-sheet/

- 10 biggest pitfalls: http://blogs.nature.com/naturejobs/2016/02/10/a-david-letterman-like-countdown-to-the-10-biggest-pitfalls-in-scientific-presentations/


<!--chapter:end:04-literature.Rmd-->

# Scientific English {#scientific_english}

## How to write clear scientific English?

The material in this section is based on @Skern2009. He suggests 8 guidelines that will help you to write in a clear and concise way:

1. Plan your writing
2. Use a clean and legible layout
3. Structure your text in paragraphs
4. Write simple sentences
5. Write positive statements
6. Write active statements
7. Omit unnecessary words
8. Read, think, write, read again and think again

## Paraphrasing of longer texts
Every sentence you paraphrase or idea you take from others' work must be references. The reader should be able to distinguish between your ideas and thoughts and others' contributions. To avoid placing references after every sentence, you might use the following style:

```{block, type = 'rmdexample'}
X and Y explain in *their paper* that agricultural fields were contaminated by microplastics (**reference**). This is a global rather than local issue so *the authors*. Therefore, *they* suggest to implement a global monitoring programm to tackle micropalstics contamination. In *the same paper*, X and Y mention that to reduce littering of microplastics the production of one-way plastics must be reduced.
```

It is clear that all the content comes from X and Y although the reference itself appears only once in the text.

Other helpful expressions for paraphrasing:

- according to the work of $\dots$
- our results accord well with $\dots$
- X and Y suggest $\dots$
- this result is also supported by X and Y (reference)


## Further reading and excercises
Read chapter 2 in @Skern2009 and do the exercises. Compare your solutions to his suggestions.




<!--chapter:end:05-scientific_english.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!-- --- -->
<!-- nocite: '@Beinke2016' -->
<!-- ... -->

<div id="refs"></div>

<!--chapter:end:06-references.Rmd-->

